{{- if and .Values.secrets (not .Values.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "isitdown.fullname" . }}-secrets
  labels:
    {{- include "isitdown.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $name, $value := .Values.secrets }}
  {{ $name }}: {{ $value | quote }}
  {{- end }}
{{- end }}
