import { cn } from "@/lib/utils";

/**
 * Magic UI's border beam (magicui.design/docs/components/border-beam),
 * generated by the shadcn CLI and then edited in place. A regeneration
 * overwrites the file and silently reverts every edit, so they are named here:
 *
 * 1. No `motion`. Upstream animates `offsetDistance` with a `motion.div`, which
 *    pulls motion's full animation feature set into the entry chunk — 23 kB
 *    gzipped over the bundle budget for one decorative loop, where the same
 *    travel is four lines of CSS (`.border-beam-run` in motion.css). The
 *    number ticker still uses motion, and still only its spring.
 * 2. Upstream's `colorFrom`/`colorTo` default to two hex literals. Colour
 *    belongs to tokens.css and test/ui/theme.test.ts scans this directory for
 *    exactly that, so the defaults read the accent ramp instead and a caller
 *    that wants severity passes `var(--status-major-outage)`.
 * 3. The prop list is cut to what this dashboard calls: an endlessly
 *    configurable transition is upstream's API surface, not ours.
 *
 * Reduced motion stops the beam dead rather than parking a bright square in
 * one corner: motion.css pins every iteration count to 1 under the preference,
 * and the keyframe ends where it started, off the visible edge. That is also
 * what keeps the visual baselines still, since the harness renders with
 * --force-prefers-reduced-motion.
 */
export interface BorderBeamProps {
  /** Length of the travelling segment, in px. */
  size?: number;
  /** Seconds for one lap. */
  duration?: number;
  /** Seconds to offset the start by, so two beams do not travel in lockstep. */
  delay?: number;
  /** Leading colour of the segment. */
  colorFrom?: string;
  /** Trailing colour of the segment. */
  colorTo?: string;
  /** Thickness of the beam's track, in px. */
  borderWidth?: number;
  className?: string;
}

export function BorderBeam({
  size = 120,
  duration = 7,
  delay = 0,
  colorFrom = "var(--color-accent-500)",
  colorTo = "var(--color-accent)",
  borderWidth = 1.5,
  className,
}: BorderBeamProps) {
  return (
    <div
      aria-hidden="true"
      className="pointer-events-none absolute inset-0 rounded-[inherit] border-(length:--border-beam-width) border-transparent mask-[linear-gradient(transparent,transparent),linear-gradient(black,black)] mask-intersect [mask-clip:padding-box,border-box]"
      style={{ "--border-beam-width": `${borderWidth}px` } as React.CSSProperties}
    >
      <div
        className={cn(
          "border-beam-run absolute aspect-square bg-linear-to-l from-(--beam-from) via-(--beam-to) to-transparent",
          className,
        )}
        style={
          {
            width: size,
            offsetPath: `rect(0 auto auto 0 round ${size}px)`,
            animationDuration: `${duration}s`,
            animationDelay: `${-delay}s`,
            "--beam-from": colorFrom,
            "--beam-to": colorTo,
          } as React.CSSProperties
        }
      />
    </div>
  );
}
