import { useId } from "react";
import { cn } from "@/lib/utils";

/**
 * Magic UI's dot pattern (magicui.design/docs/components/dot-pattern),
 * generated by the shadcn CLI and then edited in place. A regeneration
 * overwrites the file and silently reverts every edit, so they are named here:
 *
 * 1. One `<pattern>` tile instead of one `<circle>` per dot. Upstream measures
 *    the container and emits width/height ÷ spacing circles — a hero band on
 *    this dashboard is roughly 1200×260, which is 1,200 nodes of decoration
 *    under a headline. The tile paints the same grid in four.
 * 2. The glow variant is dropped with it: it is what the per-dot nodes existed
 *    for, each one carrying its own randomised infinite motion transition.
 *    Random delays also mean two renders of the same page are never the same
 *    image, which is a visual baseline that fails for reasons nobody changed.
 * 3. Upstream's `text-neutral-400/80` default is gone — a Tailwind palette
 *    literal, which test/ui/theme.test.ts scans this directory for. The dots
 *    take `currentColor`, so the caller sets the colour with a token utility.
 */
export interface DotPatternProps extends React.SVGProps<SVGSVGElement> {
  /** Horizontal spacing between dots, in px. */
  width?: number;
  /** Vertical spacing between dots, in px. */
  height?: number;
  /** Radius of each dot, in px. */
  cr?: number;
  className?: string;
}

export function DotPattern({ width = 18, height = 18, cr = 1, className, ...props }: DotPatternProps) {
  const id = useId();

  return (
    <svg
      aria-hidden="true"
      className={cn("pointer-events-none absolute inset-0 size-full", className)}
      {...props}
    >
      <defs>
        <pattern id={id} width={width} height={height} patternUnits="userSpaceOnUse">
          <circle cx={cr} cy={cr} r={cr} fill="currentColor" />
        </pattern>
      </defs>
      <rect width="100%" height="100%" fill={`url(#${id})`} />
    </svg>
  );
}
