import { useEffect, useRef, type ComponentPropsWithoutRef } from "react"
import { MotionGlobalConfig, useMotionValue, useReducedMotion, useSpring } from "motion/react"

import { cn } from "@/lib/utils"

interface NumberTickerProps extends ComponentPropsWithoutRef<"span"> {
  value: number
  locale: string
  suffix?: string
  startValue?: number
  direction?: "up" | "down"
  delay?: number
  decimalPlaces?: number
}

/**
 * Magic UI's number ticker (magicui.design/docs/components/number-ticker),
 * generated by the shadcn CLI and then edited in place. A regeneration
 * overwrites this file and silently reverts every edit, so they are named
 * here:
 *
 * 1. `locale` is a required prop; upstream hardcodes
 *    `Intl.NumberFormat("en-US")`, which renders "1,234" to an operator whose
 *    dashboard says "1.234" everywhere else. Callers pass `i18n.language`, the
 *    same way they pass it to `formatPercent` — see lib/format.ts.
 * 2. `suffix` joins the number inside one text node rather than sitting beside
 *    it as a sibling, because the spring writes `textContent` and would wipe a
 *    sibling on its first frame. It carries the "%" `formatPercent` appended.
 * 3. Upstream's `text-black dark:text-white tracking-wider` default is gone:
 *    the colour is off-palette and test/ui/theme.test.ts scans this directory
 *    for exactly that, and the tracking belongs to the call site.
 *    `tabular-nums` stays — without it every frame re-measures and the figure
 *    jitters through the count.
 * 4. The run is timed off the figure rather than left at upstream's fixed
 *    `damping: 60, stiffness: 100` — see `tickerDuration`.
 * 5. The count is skipped — the target painted on the first frame — whenever
 *    motion is switched off, either by the operator's reduced-motion
 *    preference or by `MotionGlobalConfig.skipAnimations`. motion.css already
 *    honours the preference for every other animation in the app, but a spring
 *    is invisible to a stylesheet, so it has to opt out here.
 * 6. Upstream gates the count on `useInView`, so a figure below the fold sits
 *    at its start value until the operator scrolls down to it. Here the count
 *    runs on mount instead: the dashboard is read as one screenful of figures,
 *    and a tally that only moves once looked at reads as a broken number
 *    rather than a flourish.
 */
/** Longest and shortest a count may run for, in seconds. */
const SLOWEST = 1.4
const FASTEST = 0.5
/** Seconds taken off the run for every power of ten in the figure. */
const DECADE_GAIN = 0.3

/**
 * How long a figure takes to arrive. A spring settles in the same time
 * whatever distance it covers, so a fleet of 7 and a tally of 8,500 minutes
 * used to run for exactly as long — and the big one reads as the slower of the
 * two, because its digits are still turning at a glance where the small one
 * has already landed. Timing by decade rather than by distance keeps the
 * difference legible without letting a five-figure count snap into place.
 */
export const tickerDuration = (value: number): number =>
  Math.min(SLOWEST, Math.max(FASTEST, SLOWEST - DECADE_GAIN * Math.log10(1 + Math.abs(value))))

export function NumberTicker({
  value,
  locale,
  suffix = "",
  startValue = 0,
  direction = "up",
  delay = 0,
  className,
  decimalPlaces = 0,
  ...props
}: NumberTickerProps) {
  const ref = useRef<HTMLSpanElement>(null)
  const still = useReducedMotion() === true || MotionGlobalConfig.skipAnimations === true
  const motionValue = useMotionValue(direction === "down" ? value : startValue)
  const springValue = useSpring(motionValue, {
    visualDuration: tickerDuration(value),
    bounce: 0,
  })

  const format = (latest: number): string =>
    new Intl.NumberFormat(locale, {
      minimumFractionDigits: decimalPlaces,
      maximumFractionDigits: decimalPlaces,
    }).format(Number(latest.toFixed(decimalPlaces))) + suffix

  useEffect(() => {
    let timer: ReturnType<typeof setTimeout> | null = null

    if (!still) {
      timer = setTimeout(() => {
        motionValue.set(direction === "down" ? startValue : value)
      }, delay * 1000)
    }

    return () => {
      if (timer !== null) {
        clearTimeout(timer)
      }
    }
  }, [motionValue, still, delay, value, direction, startValue])

  // Deliberately unkeyed: `format` closes over every prop that decides how a
  // frame reads, so re-subscribing each render is what keeps a locale or
  // decimal change from being written in the old shape.
  useEffect(() => {
    if (still) return
    return springValue.on("change", (latest) => {
      if (ref.current) {
        ref.current.textContent = format(latest)
      }
    })
  })

  return (
    <span ref={ref} className={cn("inline-block tabular-nums", className)} {...props}>
      {format(still ? value : startValue)}
    </span>
  )
}
